apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakthi-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sakthi-springboot
  template:
    metadata:
      labels:
        app: sakthi-springboot
    spec:
      containers:
        - name: springboot
          image: sakthi120498/sakthi-docker-demo:sakthi-docker-demo
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: sakthi-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: sakthi-springboot
